# Generated by Django 4.2 on 2024-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('major', models.CharField(blank=True, choices=[('Bar Owner', 'Matchup Stats'), ('Analyst', 'Team Comparison'), ('Gambler', 'Single Player Stats')], max_length=200)),
            ],
        ),
    ]
