# Generated by Django 4.2 on 2024-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsShare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='major',
        ),
        migrations.AddField(
            model_name='guru',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
