# Generated by Django 4.2 on 2024-04-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsShare', '0003_guru_typeguru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guru',
            old_name='typeguru',
            new_name='Type',
        ),
    ]
