# Generated by Django 4.2 on 2024-04-25 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsShare', '0006_rename_playeronestats_statsheet_playeronename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
